version: '2'
services:
  app:
    image: 'app_exercicio_1'
    build: .
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bd_exercicio
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bd_exercicio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  # Clinte db
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      - 8978:8978